"""rename address

Revision ID: 28baecc1d1b9
Revises: 3e86b4fb2579
Create Date: 2026-09-23 22:40:42.201480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28baecc1d1b9'
down_revision = '3e86b4fb2579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ### 
