"""rename department

Revision ID: 3e86b4fb2579
Revises: 592d212b0147
Create Date: 2026-09-23 22:32:46.268903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e86b4fb2579'
down_revision = '592d212b0147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
